---

- name: ensure templates dir is created
  file:
    path: "{{ es_conf_dir }}/templates"
    state: directory
    owner: root
    group: "{{ es_group }}"
    mode: "2750"

- name: Copy templates to elasticsearch
  copy: src={{ item }} dest={{ es_conf_dir }}/templates owner=root group={{ es_group }} mode=0660
  register: load_templates
  with_fileglob:
    - "{{ es_templates_fileglob | default('') }}"

- name: Install templates
  uri:
    url: "{{ es_api_uri }}/_template/{{item | filename}}"
    method: PUT
    status_code: 200
    user: "{{es_api_basic_auth_username | default(omit)}}"
    password: "{{es_api_basic_auth_password | default(omit)}}"
    force_basic_auth: yes
    body_format: json
    body: "{{ lookup('file', item) }}"
    validate_certs: "{{ es_validate_certs }}"
  when: load_templates.changed and es_start_service
  with_fileglob:
    - "{{ es_templates_fileglob | default('') }}"
  run_once: True


- name: ensure component templates dir is created
  file:
    path: "{{ es_conf_dir }}/templates/component_templates"
    state: directory
    owner: root
    group: "{{ es_group }}"
    mode: "2750"
    when: "es_component_templates_fileglob is defined and (es_component_templates_fileglob | length > 0)"

- name: Copy component templates to elasticsearch
  copy: src={{ item }} dest={{ es_conf_dir }}/templates/component_templates owner=root group={{ es_group }} mode=0660
  register: load_component_templates
  with_fileglob:
    - "{{ es_component_templates_fileglob | default('') }}"

- name: Install component templates
  uri:
    url: "{{ es_api_uri }}/_component_template/{{item | filename}}"
    method: PUT
    status_code: 200
    user: "{{es_api_basic_auth_username | default(omit)}}"
    password: "{{es_api_basic_auth_password | default(omit)}}"
    force_basic_auth: yes
    body_format: json
    body: "{{ lookup('file', item) }}"
    validate_certs: "{{ es_validate_certs }}"
  when: load_component_templates.changed and es_start_service
  with_fileglob:
    - "{{ es_component_templates_fileglob | default('') }}"
  run_once: True

- name: ensure index templates dir is created
  file:
    path: "{{ es_conf_dir }}/templates/index_templates"
    state: directory
    owner: root
    group: "{{ es_group }}"
    mode: "2750"
    when: "es_index_templates_fileglob is defined and (es_index_templates_fileglob | length > 0)"

- name: Copy index templates to elasticsearch
  copy: src={{ item }} dest={{ es_conf_dir }}/templates/index_templates owner=root group={{ es_group }} mode=0660
  register: load_index_templates
  with_fileglob:
    - "{{ es_index_templates_fileglob | default('') }}"

- name: Install index templates
  uri:
    url: "{{ es_api_uri }}/_index_template/{{item | filename}}"
    method: PUT
    status_code: 200
    user: "{{es_api_basic_auth_username | default(omit)}}"
    password: "{{es_api_basic_auth_password | default(omit)}}"
    force_basic_auth: yes
    body_format: json
    body: "{{ lookup('file', item) }}"
    validate_certs: "{{ es_validate_certs }}"
  when: load_index_templates.changed and es_start_service
  with_fileglob:
    - "{{ es_index_templates_fileglob | default('') }}"
  run_once: True